### ISSUE TITLE
incorrect colors in Terminal.app on mac osx 10.9

### ISSUE THREAD

**Issue by pryg-skok** [miripiruni/vimi#28]
Hi,

I saw your lecture at Yandex's SHRI and became interested in your vim setup. It's great ;-) and yes killer-feature of your setup is meticulously commented. Thanks.

The issue that if I use your setup on bare mac osx 10.9 in Terminal app solorized color scheme shows incorrect colors. I found that you use such configuration:
let g:solarized_termcolors=16
for iTerm2 support. But to make them correct in Terminal this line should be:
let g:solarized_termcolors=256

**Comment by miripiruni** [comment]
:walking:
